# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import modbus_wiki_pb2 as modbus__wiki__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in modbus_wiki_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModbusWikiServiceStub(object):
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSnapshot = channel.unary_unary(
                '/modbus_wiki.ModbusWikiService/GetSnapshot',
                request_serializer=modbus__wiki__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=modbus__wiki__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.StreamRegisters = channel.unary_stream(
                '/modbus_wiki.ModbusWikiService/StreamRegisters',
                request_serializer=modbus__wiki__pb2.StreamRequest.SerializeToString,
                response_deserializer=modbus__wiki__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.WriteRegister = channel.unary_unary(
                '/modbus_wiki.ModbusWikiService/WriteRegister',
                request_serializer=modbus__wiki__pb2.WriteRequest.SerializeToString,
                response_deserializer=modbus__wiki__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.GetWikiEntries = channel.unary_unary(
                '/modbus_wiki.ModbusWikiService/GetWikiEntries',
                request_serializer=modbus__wiki__pb2.WikiRequest.SerializeToString,
                response_deserializer=modbus__wiki__pb2.WikiResponse.FromString,
                _registered_method=True)


class ModbusWikiServiceServicer(object):
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────
    """

    def GetSnapshot(self, request, context):
        """One-shot snapshot – fastest single read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRegisters(self, request, context):
        """Server-streaming – continuous push for dashboards/SCADA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteRegister(self, request, context):
        """Write a single register / coil
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWikiEntries(self, request, context):
        """Wiki CRUD – knowledge base
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModbusWikiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=modbus__wiki__pb2.SnapshotRequest.FromString,
                    response_serializer=modbus__wiki__pb2.SnapshotResponse.SerializeToString,
            ),
            'StreamRegisters': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRegisters,
                    request_deserializer=modbus__wiki__pb2.StreamRequest.FromString,
                    response_serializer=modbus__wiki__pb2.SnapshotResponse.SerializeToString,
            ),
            'WriteRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteRegister,
                    request_deserializer=modbus__wiki__pb2.WriteRequest.FromString,
                    response_serializer=modbus__wiki__pb2.WriteResponse.SerializeToString,
            ),
            'GetWikiEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWikiEntries,
                    request_deserializer=modbus__wiki__pb2.WikiRequest.FromString,
                    response_serializer=modbus__wiki__pb2.WikiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modbus_wiki.ModbusWikiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modbus_wiki.ModbusWikiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModbusWikiService(object):
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────
    """

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modbus_wiki.ModbusWikiService/GetSnapshot',
            modbus__wiki__pb2.SnapshotRequest.SerializeToString,
            modbus__wiki__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRegisters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/modbus_wiki.ModbusWikiService/StreamRegisters',
            modbus__wiki__pb2.StreamRequest.SerializeToString,
            modbus__wiki__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modbus_wiki.ModbusWikiService/WriteRegister',
            modbus__wiki__pb2.WriteRequest.SerializeToString,
            modbus__wiki__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWikiEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modbus_wiki.ModbusWikiService/GetWikiEntries',
            modbus__wiki__pb2.WikiRequest.SerializeToString,
            modbus__wiki__pb2.WikiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
